name: Terraform Workflow

on:
  pull_request:
    branches:
      - main 
      
jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      # - name: Terraform Init
      #   run: terraform init

      # - name: Format Terraform files
      #   run: terraform fmt 
      
      # - name: Check Terraform formatting
      #   run: terraform fmt -check

      # - name: Validate Terraform configuration
      #   run: terraform validate
